version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - helpdesk

  config-server:
    image: romulolemes9494/config-server
    container_name: 'config-server'
    environment:
      - CONFIG_SERVER_URI=https://github.com/romulogoncalves94/helpdesk-config
      - CONFIG_SERVER_USERNAME=romulogoncalves94
      - CONFIG_SERVER_PASSWORD=
      - PORT=8888
    ports:
      - "8888:8888"
    expose:
      - 8888
    networks:
      - helpdesk

  service-discovery:
    image: romulolemes9494/service-discovery
    container_name: 'service-discovery'
    environment:
      - CONFIG_SERVER_URI=config-server:8888
    ports:
      - "8761:8761"
    expose:
      - 8761
    networks:
      - helpdesk
    depends_on:
      - config-server
    links:
      - config-server

  db:
    image: mysql:8.0
    container_name: mysql_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha_root_muito_forte
      MYSQL_DATABASE: orderservice_helpdesk
      MYSQL_USER: order_user
      MYSQL_PASSWORD: order_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  helpdesk:
    driver: bridge

volumes:
  mysql_data: