spring:
  application:
    name: 'user-service-api'
  data:
    mongodb:
      uri: 'mongodb+srv://help-desk-user:help-desk-user@clusterhelpdesk.jobdokx.mongodb.net/helpdeskdb?retryWrites=true&w=majority&appName=ClusterHelpDesk'
      auto-index-creation: true
springdoc:
  openapi:
    title: 'User Service API'
    description: 'API for managing users in the Help Desk application'
    version: '1.0.0'
