spring:
  application:
    name: email-service
mail:
  host: ${MAIL_HOST:smtp.gmail.com}
  port: ${MAIL_PORT:587}
  username: ${MAIL_USERNAME:romulolemesjw@gmail.com}
  password: ${MAIL_PASSWORD:nlue zjlj cede erox}
  protocol: ${MAIL_PROTOCOL:smtp}