spring:
  application:
    name: 'auth-serivce-api'
  data:
    mongodb:
      uri: 'mongodb+srv://help-desk-user:help-desk-user@clusterhelpdesk.jobdokx.mongodb.net/helpdeskdb?retryWrites=true&w=majority&appName=ClusterHelpDesk'

jwt.secret: 'NYUxF8Vljm1zlbNpdH/7ElecRf3HnFRWsVfBVEubw3RaZIQcsLed6Xe/wqCMgOFtwsyYms5GvbnnTh6GwdRYiZmk7QFgPZ2hYM+AXYoum8s='
jwt.expiration: 120000
jwt.expiration-sec.refresh-token: 3600

